### ISSUE TITLE
vm_describe not working

### ISSUE THREAD

**Issue by zzlyn** [Rexabit/valheim-visuals-modifier#2]
It outputs an empty file.

E.g.

```
name: ArrowWood
renderers: []
```

**Comment by Rexabit** [comment]
Is it specifically the ArrowWood prefab not displaying anything?

**Comment by Rexabit** [comment]
Was able to replicate this. The vm_describe function was skipping over the root item and looking for only skin objects.

Resolved in this commit: 87d452c

Will post to TS shortly as Version 0.1.0
