### ISSUE TITLE
Float values in color do not match the color

### ISSUE THREAD

**Issue by jpee85** [Rexabit/valheim-visuals-modifier#3]
Hey,

we are currently experimenting with your mod. We made a green version of the AxeJotunBane but it seems that the float values inside of _Color do not work correctly:

- colors: # waterdrop
    _Color: [0, **1**, 0, 1] # => results in green

- colors: # waterdrop
    _Color: [**0.1**, **1**, **0.1**, 1] # => should be also green but is something completely different.

Our configuration:

> 
> prefabName: AxeJotunBane
> icon: # Updates the icon orientation for the item when snapshot.
>   x: -90
>   y: 90
>   z: 90
> materials:
> - colors: # waterdrop
>     _Color: [0, 1, 0, 1] # 1,1,1,1
> - colors: # JotunBaneDripSplash
>     _Color: [0, 1, 0, 1] # RGBA(1.000, 1.000, 1.000, 0.472)
>     _EmissionColor: [0,1,0,1] # RGBA(0.000, 0.000, 0.000, 1.000)
> - colors: # water_drop
>     _Color: [0, 1, 0, 0] # RGBA(1.000, 1.000, 1.000, 1.000)
> - colors: # JotunBane_mat
>     _Color: [0, 1, 0, 1] # RGBA(1.000, 1.000, 1.000, 1.000)
>     _MetalColor: [0,1,0,1] # RGBA(1.000, 1.000, 1.000, 1.000)
>     _EmissionColor: [0,1,0,1] # RGBA(0.000, 0.000, 0.000, 1.000)
> - colors: # JotunbaneFlow_mat
>     _Color: [0, 1, 0, 1] # RGBA(0.000, 0.000, 0.000, 1.000)
>     _FoamColor: [0, 1, 0, 1] # RGBA(1.000, 0.786, 0.118, 1.000)
>     _EmissionColor: [0,1,0,1] # RGBA(0.000, 0.000, 0.000, 0.000)
> - colors: # JotunBaneGlow
>     _Color: [0, 1, 0, 1] # RGBA(1.000, 1.000, 1.000, 0.472)
>     _EmissionColor: [0,1,0,1] # RGBA(0.000, 0.000, 0.000, 1.000)

**Comment by Rexabit** [comment]
How the property values are applied as an end result to a material really depends on what the shader is, and what that shader is doing with the value.

The solution would be to use a different shader for that specific material, however, the configuration currently doesn't allow you to change the shader on individual materials when an item has several.

**Comment by jpee85** [comment]
Thanks for clarifying. So I will close as not a bug.
